[workspace] 
channels = [
    "dglteam/label/cu118",
    "pytorch",
    "https://conda.rosettacommons.org",
    "conda-forge",
    "nvidia"
]
platforms = ["linux-64"]
preview = ["pixi-build"]

[dependencies] 
rf_diffusion_all_atom = { path = "." }


[package] 
name = "rf_diffusion_all_atom"
version = "0.1.9"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.3.*" }


[system-requirements]
    cuda = "11.8"
